try {
    console.log('Normal')
} catch(e) {
    console.log('bad')
} finally {
    console.log('lol')
}

// плюс в том что если код выдаст ошибку то дальше другой код будет работать

console.log('working')